Vagrant.configure("2") do |config|
    config.vm.define "Jenkins" do |web01|
      web01.vm.box = "bento/ubuntu-22.04"
      web01.vm.hostname = "Jenkins"
      web01.vm.network "private_network", ip: "192.168.56.41"
    end
  
    config.vm.define "Docker" do |web02|
      web02.vm.box = "bento/ubuntu-22.04"
      web02.vm.hostname = "Docker"
      web02.vm.network "private_network", ip: "192.168.56.42"
    end
 end
  